# Generated by Django 4.1.5 on 2023-01-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_best_quality_top_delete_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text_to_Youtube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text_wrap', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
