# Generated by Django 4.1.5 on 2023-01-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_text_to_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_to_youtube',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
