# Generated by Django 4.1.5 on 2023-01-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_text_to_youtube_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_to_youtube',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
